name: Godot PCK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
        unzip Godot_v4.4.1-stable_linux.x86_64.zip
        chmod +x Godot_v4.4.1-stable_linux.x86_64

    - name: Create PCK file
      run: |
        ./Godot_v4.4.1-stable_linux.x86_64 --export-pack Android project.pck . --headless
    - name: Upload PCK file
      uses: actions/upload-artifact@v4
      with:
        name: project-pck
        path: project.pck
